name: SonarCloud Scan

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository with all branches and full history
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Set up Node.js (required for NX)
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Derive Nx SHAs
        uses: nrwl/nx-set-shas@3e9ad7370203c1e93d109be57f3b72eb0eb511b1
        with:
          main-branch-name: main

      # Run tests for affected apps and libs
      - name: Run affected tests with coverage
        run: npx nx affected --target=test --base=$NX_BASE --head=$NX_HEAD --configuration=ci

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.PROJECT_KEY }}
            -Dsonar.organization=frankpeterandrae
            -Dsonar.sources=apps,libs
            -Dsonar.tests=apps,libs
            -Dsonar.test.inclusions=**/*.spec.ts,**/*.test-setup.ts
            -Dsonar.coverage.exclusions=**/*.js,**/main.ts,**/*environment*.ts,**/*.scss,**/*.css,**/*.json,**/demo-e2e/**,**/homepage-e2e/**,**/*test-setup.ts,**/*app.config.ts,**/*app.routes.ts,**/*.php
            -Dsonar.javascript.lcov.reportPaths=coverage/**/lcov.info
